### ISSUE TITLE
Handle id doesn't match scenario 

### ISSUE THREAD

**Issue by Rai-shwith** [Rai-shwith/get-my-attendance#5]
When user tried to register with wrong Id it shows 'registered ' change that to appropriate information.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the handleRegistration function to provide more specific error messages when a user tries to register with incorrect information. Updated the error messages to be more informative and appropriate.

You can review changes in this commit: https://github.com/lattaai12/Rai-shwith-get-my-attendance-5/commit/bf8a0b700a3ae371d795bcaea689bd389f624ca0.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
